apiVersion: skaffold/v2beta16
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local: # can only have one of this "local" or "googleCloudBuild" at 1 time
    push: false # don't push it to dockerhub (default)
  # googleCloudBuild:
  #   projectId: ticketing-dev-342504
  artifacts:
    - image: keitran0401/auth # if google cloud: us.gcr.io/ticketing-dev-342504/auth
      context: auth # the folder
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' # files that skaffold need to watch
            dest: . # corresponding path like above
    - image: keitran0401/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: keitran0401/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: keitran0401/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: keitran0401/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: keitran0401/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
